[package]
edition = "2021"
name = "shared"
version = "0.0.1"

[dependencies]
anyhow = "1.0"
tokio = "1.20"
protobuf = { version = "3.1", features = ["with-bytes"] }
bytes = "1.2"

[build-dependencies]
protobuf-codegen = { version = "3.1" }